### ISSUE TITLE
General list of things you should (and shouldn't do)

### ISSUE THREAD

**Issue by tilda** [memework/Atomic-Discord#1]
**DO:**

- Allow email/pw login (not sure how you would implement but it's good idea.)
- try to make it like a client. (Allow switching servers via a scroll bar or search for server name) (or other things)

**DON'T:**

- take someone's token (obvs)
- post to discord 2fa endpoints (if you do, you get beaned)

This list will be probably updated time to time.

**Comment by Mstrodl** [comment]
@xshotD Thanks! Email/PW login can be done through Discord API (At least I know d.js can do it)

Can you elaborate on the 2FA thing?

**Comment by tilda** [comment]
hammerandchisel/discord-api-docs#69 - jhgg's 2nd comment (scroll down a bit)

**Comment by Mstrodl** [comment]
Oh man. That sucks...

**Comment by tilda** [comment]
It kind of does, but there would probably be a bit of abuse if the 2FA endpoints were open.

**Comment by Mstrodl** [comment]
Yeah. I just need to find a way to check before allowing user login

**Comment by tilda** [comment]
This issue has moved to https://git.memework.org/heatingdevice/atomic-discord/issues/1
